# SPDX-FileCopyrightText: 2021 Lutris Engineering, Inc
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Piper McCorkle <piper@lutris.engineering>

name: Validate CITATION.cff file
description: "Validate your repository's CITATION.cff file against the schema"
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
    - run: pip install ruamel.yaml jsonschema
      shell: bash
    - run: mkdir .validate-cff
      shell: bash
    - run: wget https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/{examples/validator.py,schema.json}
      working-directory: ./.validate-cff
      shell: bash
    - run: python .validate-cff/validator.py -s .validate-cff/schema.json -d CITATION.cff
      shell: bash
